spring:
  cloud:
    config:
      server:
        bootstrap: true
  application:
    name: sedocument_config_server  
  profiles:
    active: native
    
      
server:
   port: 9002
   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9003/eureka/